# https://golangci-lint.run/usage/configuration/
run:
  timeout: 5m # 1m default times out on github-action runners

output:
  # Sort results by: filepath, line and column.
  sort-results: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
  # TODO: remove once the `performance_tests` module compiles
  # TODO: ^^^^^^ also uncomment the windows github lint action for src/bosh-dns
  - performance_tests/*
