# TODO: remove when Jammy goes EOL
- type: replace
  path: /instance_groups/name=bosh-dns/jobs/name=bosh-dns/properties/address
  value: 0.0.0.0

- type: replace
  path: /instance_groups/name=bosh-dns/jobs/name=bosh-dns/properties/configure_systemd_resolved
  value: false

- type: replace
  path: /instance_groups/name=bosh-dns/jobs/name=bosh-dns/properties/override_nameserver
  value: true
