---
platform: linux

inputs:
  - name: bosh-dns-release
  - name: bbl-state
  - name: bosh-stemcell-windows
  - name: linux-stemcell
  - name: candidate-release

params:
  CI_BBL_STATE: bbl-state

run:
  path: bosh-dns-release/ci/tasks/windows/setup-deploy.sh
