---
platform: linux

inputs:
  - name: bbl-state
  - name: bosh-dns-release

run:
  path: bosh-dns-release/ci/tasks/windows/test-acceptance-windows-nameserver-disabled.sh

params:
  CI_BBL_STATE: bbl-state
  WINDOWS_OS_VERSION:
