---
platform: windows

params:
  BOSH_DNS_RECURSOR_ADDRESS:

inputs:
- name: bosh-dns-release

run:
  path: powershell
  args:
  - "-ExecutionPolicy"
  - "Bypass"
  - "-File"
  - bosh-dns-release/ci/tasks/windows/test-unit.ps1
