---
platform: linux

inputs:
  - name: bosh-dns-release
  - name: candidate-release
  - name: bosh-stemcell
  - name: bosh-candidate-release

params:
  BASE_STEMCELL: ubuntu-jammy

run:
  path: bosh-dns-release/ci/tasks/test-acceptance.sh
