// Code generated by counterfeiter. DO NOT EDIT.
package healthinessfakes

import (
	"bosh-dns/dns/server/healthiness"
	"bosh-dns/healthcheck/api"
	"sync"
)

type FakeHealthChecker struct {
	GetStatusStub        func(ip string) api.HealthStatus
	getStatusMutex       sync.RWMutex
	getStatusArgsForCall []struct {
		ip string
	}
	getStatusReturns struct {
		result1 api.HealthStatus
	}
	getStatusReturnsOnCall map[int]struct {
		result1 api.HealthStatus
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeHealthChecker) GetStatus(ip string) api.HealthStatus {
	fake.getStatusMutex.Lock()
	ret, specificReturn := fake.getStatusReturnsOnCall[len(fake.getStatusArgsForCall)]
	fake.getStatusArgsForCall = append(fake.getStatusArgsForCall, struct {
		ip string
	}{ip})
	fake.recordInvocation("GetStatus", []interface{}{ip})
	fake.getStatusMutex.Unlock()
	if fake.GetStatusStub != nil {
		return fake.GetStatusStub(ip)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.getStatusReturns.result1
}

func (fake *FakeHealthChecker) GetStatusCallCount() int {
	fake.getStatusMutex.RLock()
	defer fake.getStatusMutex.RUnlock()
	return len(fake.getStatusArgsForCall)
}

func (fake *FakeHealthChecker) GetStatusArgsForCall(i int) string {
	fake.getStatusMutex.RLock()
	defer fake.getStatusMutex.RUnlock()
	return fake.getStatusArgsForCall[i].ip
}

func (fake *FakeHealthChecker) GetStatusReturns(result1 api.HealthStatus) {
	fake.GetStatusStub = nil
	fake.getStatusReturns = struct {
		result1 api.HealthStatus
	}{result1}
}

func (fake *FakeHealthChecker) GetStatusReturnsOnCall(i int, result1 api.HealthStatus) {
	fake.GetStatusStub = nil
	if fake.getStatusReturnsOnCall == nil {
		fake.getStatusReturnsOnCall = make(map[int]struct {
			result1 api.HealthStatus
		})
	}
	fake.getStatusReturnsOnCall[i] = struct {
		result1 api.HealthStatus
	}{result1}
}

func (fake *FakeHealthChecker) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getStatusMutex.RLock()
	defer fake.getStatusMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeHealthChecker) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ healthiness.HealthChecker = new(FakeHealthChecker)
