// Code generated by counterfeiter. DO NOT EDIT.
package healthinessfakes

import (
	"bosh-dns/dns/server/healthiness"
	"sync"
)

type FakeHealthWatcher struct {
	HealthStateStub        func(ip string) healthiness.HealthState
	healthStateMutex       sync.RWMutex
	healthStateArgsForCall []struct {
		ip string
	}
	healthStateReturns struct {
		result1 healthiness.HealthState
	}
	healthStateReturnsOnCall map[int]struct {
		result1 healthiness.HealthState
	}
	HealthStateStringStub        func(ip string) string
	healthStateStringMutex       sync.RWMutex
	healthStateStringArgsForCall []struct {
		ip string
	}
	healthStateStringReturns struct {
		result1 string
	}
	healthStateStringReturnsOnCall map[int]struct {
		result1 string
	}
	TrackStub        func(ip string)
	trackMutex       sync.RWMutex
	trackArgsForCall []struct {
		ip string
	}
	UntrackStub        func(ip string)
	untrackMutex       sync.RWMutex
	untrackArgsForCall []struct {
		ip string
	}
	RunStub        func(signal <-chan struct{})
	runMutex       sync.RWMutex
	runArgsForCall []struct {
		signal <-chan struct{}
	}
	RunCheckStub        func(ip string)
	runCheckMutex       sync.RWMutex
	runCheckArgsForCall []struct {
		ip string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeHealthWatcher) HealthState(ip string) healthiness.HealthState {
	fake.healthStateMutex.Lock()
	ret, specificReturn := fake.healthStateReturnsOnCall[len(fake.healthStateArgsForCall)]
	fake.healthStateArgsForCall = append(fake.healthStateArgsForCall, struct {
		ip string
	}{ip})
	fake.recordInvocation("HealthState", []interface{}{ip})
	fake.healthStateMutex.Unlock()
	if fake.HealthStateStub != nil {
		return fake.HealthStateStub(ip)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.healthStateReturns.result1
}

func (fake *FakeHealthWatcher) HealthStateCallCount() int {
	fake.healthStateMutex.RLock()
	defer fake.healthStateMutex.RUnlock()
	return len(fake.healthStateArgsForCall)
}

func (fake *FakeHealthWatcher) HealthStateArgsForCall(i int) string {
	fake.healthStateMutex.RLock()
	defer fake.healthStateMutex.RUnlock()
	return fake.healthStateArgsForCall[i].ip
}

func (fake *FakeHealthWatcher) HealthStateReturns(result1 healthiness.HealthState) {
	fake.HealthStateStub = nil
	fake.healthStateReturns = struct {
		result1 healthiness.HealthState
	}{result1}
}

func (fake *FakeHealthWatcher) HealthStateReturnsOnCall(i int, result1 healthiness.HealthState) {
	fake.HealthStateStub = nil
	if fake.healthStateReturnsOnCall == nil {
		fake.healthStateReturnsOnCall = make(map[int]struct {
			result1 healthiness.HealthState
		})
	}
	fake.healthStateReturnsOnCall[i] = struct {
		result1 healthiness.HealthState
	}{result1}
}

func (fake *FakeHealthWatcher) HealthStateString(ip string) string {
	fake.healthStateStringMutex.Lock()
	ret, specificReturn := fake.healthStateStringReturnsOnCall[len(fake.healthStateStringArgsForCall)]
	fake.healthStateStringArgsForCall = append(fake.healthStateStringArgsForCall, struct {
		ip string
	}{ip})
	fake.recordInvocation("HealthStateString", []interface{}{ip})
	fake.healthStateStringMutex.Unlock()
	if fake.HealthStateStringStub != nil {
		return fake.HealthStateStringStub(ip)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.healthStateStringReturns.result1
}

func (fake *FakeHealthWatcher) HealthStateStringCallCount() int {
	fake.healthStateStringMutex.RLock()
	defer fake.healthStateStringMutex.RUnlock()
	return len(fake.healthStateStringArgsForCall)
}

func (fake *FakeHealthWatcher) HealthStateStringArgsForCall(i int) string {
	fake.healthStateStringMutex.RLock()
	defer fake.healthStateStringMutex.RUnlock()
	return fake.healthStateStringArgsForCall[i].ip
}

func (fake *FakeHealthWatcher) HealthStateStringReturns(result1 string) {
	fake.HealthStateStringStub = nil
	fake.healthStateStringReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeHealthWatcher) HealthStateStringReturnsOnCall(i int, result1 string) {
	fake.HealthStateStringStub = nil
	if fake.healthStateStringReturnsOnCall == nil {
		fake.healthStateStringReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.healthStateStringReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeHealthWatcher) Track(ip string) {
	fake.trackMutex.Lock()
	fake.trackArgsForCall = append(fake.trackArgsForCall, struct {
		ip string
	}{ip})
	fake.recordInvocation("Track", []interface{}{ip})
	fake.trackMutex.Unlock()
	if fake.TrackStub != nil {
		fake.TrackStub(ip)
	}
}

func (fake *FakeHealthWatcher) TrackCallCount() int {
	fake.trackMutex.RLock()
	defer fake.trackMutex.RUnlock()
	return len(fake.trackArgsForCall)
}

func (fake *FakeHealthWatcher) TrackArgsForCall(i int) string {
	fake.trackMutex.RLock()
	defer fake.trackMutex.RUnlock()
	return fake.trackArgsForCall[i].ip
}

func (fake *FakeHealthWatcher) Untrack(ip string) {
	fake.untrackMutex.Lock()
	fake.untrackArgsForCall = append(fake.untrackArgsForCall, struct {
		ip string
	}{ip})
	fake.recordInvocation("Untrack", []interface{}{ip})
	fake.untrackMutex.Unlock()
	if fake.UntrackStub != nil {
		fake.UntrackStub(ip)
	}
}

func (fake *FakeHealthWatcher) UntrackCallCount() int {
	fake.untrackMutex.RLock()
	defer fake.untrackMutex.RUnlock()
	return len(fake.untrackArgsForCall)
}

func (fake *FakeHealthWatcher) UntrackArgsForCall(i int) string {
	fake.untrackMutex.RLock()
	defer fake.untrackMutex.RUnlock()
	return fake.untrackArgsForCall[i].ip
}

func (fake *FakeHealthWatcher) Run(signal <-chan struct{}) {
	fake.runMutex.Lock()
	fake.runArgsForCall = append(fake.runArgsForCall, struct {
		signal <-chan struct{}
	}{signal})
	fake.recordInvocation("Run", []interface{}{signal})
	fake.runMutex.Unlock()
	if fake.RunStub != nil {
		fake.RunStub(signal)
	}
}

func (fake *FakeHealthWatcher) RunCallCount() int {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	return len(fake.runArgsForCall)
}

func (fake *FakeHealthWatcher) RunArgsForCall(i int) <-chan struct{} {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	return fake.runArgsForCall[i].signal
}

func (fake *FakeHealthWatcher) RunCheck(ip string) {
	fake.runCheckMutex.Lock()
	fake.runCheckArgsForCall = append(fake.runCheckArgsForCall, struct {
		ip string
	}{ip})
	fake.recordInvocation("RunCheck", []interface{}{ip})
	fake.runCheckMutex.Unlock()
	if fake.RunCheckStub != nil {
		fake.RunCheckStub(ip)
	}
}

func (fake *FakeHealthWatcher) RunCheckCallCount() int {
	fake.runCheckMutex.RLock()
	defer fake.runCheckMutex.RUnlock()
	return len(fake.runCheckArgsForCall)
}

func (fake *FakeHealthWatcher) RunCheckArgsForCall(i int) string {
	fake.runCheckMutex.RLock()
	defer fake.runCheckMutex.RUnlock()
	return fake.runCheckArgsForCall[i].ip
}

func (fake *FakeHealthWatcher) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.healthStateMutex.RLock()
	defer fake.healthStateMutex.RUnlock()
	fake.healthStateStringMutex.RLock()
	defer fake.healthStateStringMutex.RUnlock()
	fake.trackMutex.RLock()
	defer fake.trackMutex.RUnlock()
	fake.untrackMutex.RLock()
	defer fake.untrackMutex.RUnlock()
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	fake.runCheckMutex.RLock()
	defer fake.runCheckMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeHealthWatcher) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ healthiness.HealthWatcher = new(FakeHealthWatcher)
