// This file was generated by counterfeiter
package managerfakes

import (
	"dns/manager"
	"sync"
)

type FakeDNSManager struct {
	SetPrimaryStub        func(string) error
	setPrimaryMutex       sync.RWMutex
	setPrimaryArgsForCall []struct {
		arg1 string
	}
	setPrimaryReturns struct {
		result1 error
	}
	ReadStub        func() ([]string, error)
	readMutex       sync.RWMutex
	readArgsForCall []struct{}
	readReturns     struct {
		result1 []string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeDNSManager) SetPrimary(arg1 string) error {
	fake.setPrimaryMutex.Lock()
	fake.setPrimaryArgsForCall = append(fake.setPrimaryArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("SetPrimary", []interface{}{arg1})
	fake.setPrimaryMutex.Unlock()
	if fake.SetPrimaryStub != nil {
		return fake.SetPrimaryStub(arg1)
	} else {
		return fake.setPrimaryReturns.result1
	}
}

func (fake *FakeDNSManager) SetPrimaryCallCount() int {
	fake.setPrimaryMutex.RLock()
	defer fake.setPrimaryMutex.RUnlock()
	return len(fake.setPrimaryArgsForCall)
}

func (fake *FakeDNSManager) SetPrimaryArgsForCall(i int) string {
	fake.setPrimaryMutex.RLock()
	defer fake.setPrimaryMutex.RUnlock()
	return fake.setPrimaryArgsForCall[i].arg1
}

func (fake *FakeDNSManager) SetPrimaryReturns(result1 error) {
	fake.SetPrimaryStub = nil
	fake.setPrimaryReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeDNSManager) Read() ([]string, error) {
	fake.readMutex.Lock()
	fake.readArgsForCall = append(fake.readArgsForCall, struct{}{})
	fake.recordInvocation("Read", []interface{}{})
	fake.readMutex.Unlock()
	if fake.ReadStub != nil {
		return fake.ReadStub()
	} else {
		return fake.readReturns.result1, fake.readReturns.result2
	}
}

func (fake *FakeDNSManager) ReadCallCount() int {
	fake.readMutex.RLock()
	defer fake.readMutex.RUnlock()
	return len(fake.readArgsForCall)
}

func (fake *FakeDNSManager) ReadReturns(result1 []string, result2 error) {
	fake.ReadStub = nil
	fake.readReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeDNSManager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.setPrimaryMutex.RLock()
	defer fake.setPrimaryMutex.RUnlock()
	fake.readMutex.RLock()
	defer fake.readMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeDNSManager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ manager.DNSManager = new(FakeDNSManager)
