// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"
)

type Healther struct {
	TrackStub        func(ip string)
	trackMutex       sync.RWMutex
	trackArgsForCall []struct {
		ip string
	}
	UntrackStub        func(ip string)
	untrackMutex       sync.RWMutex
	untrackArgsForCall []struct {
		ip string
	}
	IsHealthyStub        func(ip string) *bool
	isHealthyMutex       sync.RWMutex
	isHealthyArgsForCall []struct {
		ip string
	}
	isHealthyReturns struct {
		result1 *bool
	}
	isHealthyReturnsOnCall map[int]struct {
		result1 *bool
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Healther) Track(ip string) {
	fake.trackMutex.Lock()
	fake.trackArgsForCall = append(fake.trackArgsForCall, struct {
		ip string
	}{ip})
	fake.recordInvocation("Track", []interface{}{ip})
	fake.trackMutex.Unlock()
	if fake.TrackStub != nil {
		fake.TrackStub(ip)
	}
}

func (fake *Healther) TrackCallCount() int {
	fake.trackMutex.RLock()
	defer fake.trackMutex.RUnlock()
	return len(fake.trackArgsForCall)
}

func (fake *Healther) TrackArgsForCall(i int) string {
	fake.trackMutex.RLock()
	defer fake.trackMutex.RUnlock()
	return fake.trackArgsForCall[i].ip
}

func (fake *Healther) Untrack(ip string) {
	fake.untrackMutex.Lock()
	fake.untrackArgsForCall = append(fake.untrackArgsForCall, struct {
		ip string
	}{ip})
	fake.recordInvocation("Untrack", []interface{}{ip})
	fake.untrackMutex.Unlock()
	if fake.UntrackStub != nil {
		fake.UntrackStub(ip)
	}
}

func (fake *Healther) UntrackCallCount() int {
	fake.untrackMutex.RLock()
	defer fake.untrackMutex.RUnlock()
	return len(fake.untrackArgsForCall)
}

func (fake *Healther) UntrackArgsForCall(i int) string {
	fake.untrackMutex.RLock()
	defer fake.untrackMutex.RUnlock()
	return fake.untrackArgsForCall[i].ip
}

func (fake *Healther) IsHealthy(ip string) *bool {
	fake.isHealthyMutex.Lock()
	ret, specificReturn := fake.isHealthyReturnsOnCall[len(fake.isHealthyArgsForCall)]
	fake.isHealthyArgsForCall = append(fake.isHealthyArgsForCall, struct {
		ip string
	}{ip})
	fake.recordInvocation("IsHealthy", []interface{}{ip})
	fake.isHealthyMutex.Unlock()
	if fake.IsHealthyStub != nil {
		return fake.IsHealthyStub(ip)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.isHealthyReturns.result1
}

func (fake *Healther) IsHealthyCallCount() int {
	fake.isHealthyMutex.RLock()
	defer fake.isHealthyMutex.RUnlock()
	return len(fake.isHealthyArgsForCall)
}

func (fake *Healther) IsHealthyArgsForCall(i int) string {
	fake.isHealthyMutex.RLock()
	defer fake.isHealthyMutex.RUnlock()
	return fake.isHealthyArgsForCall[i].ip
}

func (fake *Healther) IsHealthyReturns(result1 *bool) {
	fake.IsHealthyStub = nil
	fake.isHealthyReturns = struct {
		result1 *bool
	}{result1}
}

func (fake *Healther) IsHealthyReturnsOnCall(i int, result1 *bool) {
	fake.IsHealthyStub = nil
	if fake.isHealthyReturnsOnCall == nil {
		fake.isHealthyReturnsOnCall = make(map[int]struct {
			result1 *bool
		})
	}
	fake.isHealthyReturnsOnCall[i] = struct {
		result1 *bool
	}{result1}
}

func (fake *Healther) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.trackMutex.RLock()
	defer fake.trackMutex.RUnlock()
	fake.untrackMutex.RLock()
	defer fake.untrackMutex.RUnlock()
	fake.isHealthyMutex.RLock()
	defer fake.isHealthyMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Healther) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
