// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"
)

type Healther struct {
	TrackStub        func(string)
	trackMutex       sync.RWMutex
	trackArgsForCall []struct {
		arg1 string
	}
	UntrackStub        func(string)
	untrackMutex       sync.RWMutex
	untrackArgsForCall []struct {
		arg1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Healther) Track(arg1 string) {
	fake.trackMutex.Lock()
	fake.trackArgsForCall = append(fake.trackArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.TrackStub
	fake.recordInvocation("Track", []interface{}{arg1})
	fake.trackMutex.Unlock()
	if stub != nil {
		fake.TrackStub(arg1)
	}
}

func (fake *Healther) TrackCallCount() int {
	fake.trackMutex.RLock()
	defer fake.trackMutex.RUnlock()
	return len(fake.trackArgsForCall)
}

func (fake *Healther) TrackCalls(stub func(string)) {
	fake.trackMutex.Lock()
	defer fake.trackMutex.Unlock()
	fake.TrackStub = stub
}

func (fake *Healther) TrackArgsForCall(i int) string {
	fake.trackMutex.RLock()
	defer fake.trackMutex.RUnlock()
	argsForCall := fake.trackArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Healther) Untrack(arg1 string) {
	fake.untrackMutex.Lock()
	fake.untrackArgsForCall = append(fake.untrackArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.UntrackStub
	fake.recordInvocation("Untrack", []interface{}{arg1})
	fake.untrackMutex.Unlock()
	if stub != nil {
		fake.UntrackStub(arg1)
	}
}

func (fake *Healther) UntrackCallCount() int {
	fake.untrackMutex.RLock()
	defer fake.untrackMutex.RUnlock()
	return len(fake.untrackArgsForCall)
}

func (fake *Healther) UntrackCalls(stub func(string)) {
	fake.untrackMutex.Lock()
	defer fake.untrackMutex.Unlock()
	fake.UntrackStub = stub
}

func (fake *Healther) UntrackArgsForCall(i int) string {
	fake.untrackMutex.RLock()
	defer fake.untrackMutex.RUnlock()
	argsForCall := fake.untrackArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Healther) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.trackMutex.RLock()
	defer fake.trackMutex.RUnlock()
	fake.untrackMutex.RLock()
	defer fake.untrackMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Healther) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
