// Code generated by counterfeiter. DO NOT EDIT.
package apifakes

import (
	"bosh-dns/dns/api"
	"bosh-dns/dns/server/records"
	"sync"
)

type FakeRecordManager struct {
	FilterStub        func(aliasExpansions []string, shouldTrack bool) ([]records.Record, error)
	filterMutex       sync.RWMutex
	filterArgsForCall []struct {
		aliasExpansions []string
		shouldTrack     bool
	}
	filterReturns struct {
		result1 []records.Record
		result2 error
	}
	filterReturnsOnCall map[int]struct {
		result1 []records.Record
		result2 error
	}
	AllRecordsStub        func() *[]records.Record
	allRecordsMutex       sync.RWMutex
	allRecordsArgsForCall []struct{}
	allRecordsReturns     struct {
		result1 *[]records.Record
	}
	allRecordsReturnsOnCall map[int]struct {
		result1 *[]records.Record
	}
	ExpandAliasesStub        func(fqdn string) []string
	expandAliasesMutex       sync.RWMutex
	expandAliasesArgsForCall []struct {
		fqdn string
	}
	expandAliasesReturns struct {
		result1 []string
	}
	expandAliasesReturnsOnCall map[int]struct {
		result1 []string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeRecordManager) Filter(aliasExpansions []string, shouldTrack bool) ([]records.Record, error) {
	var aliasExpansionsCopy []string
	if aliasExpansions != nil {
		aliasExpansionsCopy = make([]string, len(aliasExpansions))
		copy(aliasExpansionsCopy, aliasExpansions)
	}
	fake.filterMutex.Lock()
	ret, specificReturn := fake.filterReturnsOnCall[len(fake.filterArgsForCall)]
	fake.filterArgsForCall = append(fake.filterArgsForCall, struct {
		aliasExpansions []string
		shouldTrack     bool
	}{aliasExpansionsCopy, shouldTrack})
	fake.recordInvocation("Filter", []interface{}{aliasExpansionsCopy, shouldTrack})
	fake.filterMutex.Unlock()
	if fake.FilterStub != nil {
		return fake.FilterStub(aliasExpansions, shouldTrack)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.filterReturns.result1, fake.filterReturns.result2
}

func (fake *FakeRecordManager) FilterCallCount() int {
	fake.filterMutex.RLock()
	defer fake.filterMutex.RUnlock()
	return len(fake.filterArgsForCall)
}

func (fake *FakeRecordManager) FilterArgsForCall(i int) ([]string, bool) {
	fake.filterMutex.RLock()
	defer fake.filterMutex.RUnlock()
	return fake.filterArgsForCall[i].aliasExpansions, fake.filterArgsForCall[i].shouldTrack
}

func (fake *FakeRecordManager) FilterReturns(result1 []records.Record, result2 error) {
	fake.FilterStub = nil
	fake.filterReturns = struct {
		result1 []records.Record
		result2 error
	}{result1, result2}
}

func (fake *FakeRecordManager) FilterReturnsOnCall(i int, result1 []records.Record, result2 error) {
	fake.FilterStub = nil
	if fake.filterReturnsOnCall == nil {
		fake.filterReturnsOnCall = make(map[int]struct {
			result1 []records.Record
			result2 error
		})
	}
	fake.filterReturnsOnCall[i] = struct {
		result1 []records.Record
		result2 error
	}{result1, result2}
}

func (fake *FakeRecordManager) AllRecords() *[]records.Record {
	fake.allRecordsMutex.Lock()
	ret, specificReturn := fake.allRecordsReturnsOnCall[len(fake.allRecordsArgsForCall)]
	fake.allRecordsArgsForCall = append(fake.allRecordsArgsForCall, struct{}{})
	fake.recordInvocation("AllRecords", []interface{}{})
	fake.allRecordsMutex.Unlock()
	if fake.AllRecordsStub != nil {
		return fake.AllRecordsStub()
	}
	if specificReturn {
		return ret.result1
	}
	return fake.allRecordsReturns.result1
}

func (fake *FakeRecordManager) AllRecordsCallCount() int {
	fake.allRecordsMutex.RLock()
	defer fake.allRecordsMutex.RUnlock()
	return len(fake.allRecordsArgsForCall)
}

func (fake *FakeRecordManager) AllRecordsReturns(result1 *[]records.Record) {
	fake.AllRecordsStub = nil
	fake.allRecordsReturns = struct {
		result1 *[]records.Record
	}{result1}
}

func (fake *FakeRecordManager) AllRecordsReturnsOnCall(i int, result1 *[]records.Record) {
	fake.AllRecordsStub = nil
	if fake.allRecordsReturnsOnCall == nil {
		fake.allRecordsReturnsOnCall = make(map[int]struct {
			result1 *[]records.Record
		})
	}
	fake.allRecordsReturnsOnCall[i] = struct {
		result1 *[]records.Record
	}{result1}
}

func (fake *FakeRecordManager) ExpandAliases(fqdn string) []string {
	fake.expandAliasesMutex.Lock()
	ret, specificReturn := fake.expandAliasesReturnsOnCall[len(fake.expandAliasesArgsForCall)]
	fake.expandAliasesArgsForCall = append(fake.expandAliasesArgsForCall, struct {
		fqdn string
	}{fqdn})
	fake.recordInvocation("ExpandAliases", []interface{}{fqdn})
	fake.expandAliasesMutex.Unlock()
	if fake.ExpandAliasesStub != nil {
		return fake.ExpandAliasesStub(fqdn)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.expandAliasesReturns.result1
}

func (fake *FakeRecordManager) ExpandAliasesCallCount() int {
	fake.expandAliasesMutex.RLock()
	defer fake.expandAliasesMutex.RUnlock()
	return len(fake.expandAliasesArgsForCall)
}

func (fake *FakeRecordManager) ExpandAliasesArgsForCall(i int) string {
	fake.expandAliasesMutex.RLock()
	defer fake.expandAliasesMutex.RUnlock()
	return fake.expandAliasesArgsForCall[i].fqdn
}

func (fake *FakeRecordManager) ExpandAliasesReturns(result1 []string) {
	fake.ExpandAliasesStub = nil
	fake.expandAliasesReturns = struct {
		result1 []string
	}{result1}
}

func (fake *FakeRecordManager) ExpandAliasesReturnsOnCall(i int, result1 []string) {
	fake.ExpandAliasesStub = nil
	if fake.expandAliasesReturnsOnCall == nil {
		fake.expandAliasesReturnsOnCall = make(map[int]struct {
			result1 []string
		})
	}
	fake.expandAliasesReturnsOnCall[i] = struct {
		result1 []string
	}{result1}
}

func (fake *FakeRecordManager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.filterMutex.RLock()
	defer fake.filterMutex.RUnlock()
	fake.allRecordsMutex.RLock()
	defer fake.allRecordsMutex.RUnlock()
	fake.expandAliasesMutex.RLock()
	defer fake.expandAliasesMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeRecordManager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ api.RecordManager = new(FakeRecordManager)
