// Code generated by counterfeiter. DO NOT EDIT.
package recordsfakes

import (
	"bosh-dns/dns/server/criteria"
	"bosh-dns/dns/server/record"
	"bosh-dns/dns/server/records"
	"sync"
)

type FakeFilterer struct {
	FilterStub        func(crit criteria.MatchMaker, recs []record.Record) []record.Record
	filterMutex       sync.RWMutex
	filterArgsForCall []struct {
		crit criteria.MatchMaker
		recs []record.Record
	}
	filterReturns struct {
		result1 []record.Record
	}
	filterReturnsOnCall map[int]struct {
		result1 []record.Record
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeFilterer) Filter(crit criteria.MatchMaker, recs []record.Record) []record.Record {
	var recsCopy []record.Record
	if recs != nil {
		recsCopy = make([]record.Record, len(recs))
		copy(recsCopy, recs)
	}
	fake.filterMutex.Lock()
	ret, specificReturn := fake.filterReturnsOnCall[len(fake.filterArgsForCall)]
	fake.filterArgsForCall = append(fake.filterArgsForCall, struct {
		crit criteria.MatchMaker
		recs []record.Record
	}{crit, recsCopy})
	fake.recordInvocation("Filter", []interface{}{crit, recsCopy})
	fake.filterMutex.Unlock()
	if fake.FilterStub != nil {
		return fake.FilterStub(crit, recs)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.filterReturns.result1
}

func (fake *FakeFilterer) FilterCallCount() int {
	fake.filterMutex.RLock()
	defer fake.filterMutex.RUnlock()
	return len(fake.filterArgsForCall)
}

func (fake *FakeFilterer) FilterArgsForCall(i int) (criteria.MatchMaker, []record.Record) {
	fake.filterMutex.RLock()
	defer fake.filterMutex.RUnlock()
	return fake.filterArgsForCall[i].crit, fake.filterArgsForCall[i].recs
}

func (fake *FakeFilterer) FilterReturns(result1 []record.Record) {
	fake.FilterStub = nil
	fake.filterReturns = struct {
		result1 []record.Record
	}{result1}
}

func (fake *FakeFilterer) FilterReturnsOnCall(i int, result1 []record.Record) {
	fake.FilterStub = nil
	if fake.filterReturnsOnCall == nil {
		fake.filterReturnsOnCall = make(map[int]struct {
			result1 []record.Record
		})
	}
	fake.filterReturnsOnCall[i] = struct {
		result1 []record.Record
	}{result1}
}

func (fake *FakeFilterer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.filterMutex.RLock()
	defer fake.filterMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeFilterer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ records.Filterer = new(FakeFilterer)
