#!/usr/bin/env bash
set -eu -o pipefail

REPO_DIR="$( cd "$( dirname "${0}" )" && cd .. && pwd )"

IMAGE="${IMAGE:-"bosh/integration"}" # See ci/pipeline.yml
MOUNT_POINT="/tmp/$(basename "${REPO_DIR}")"
COMMAND=( "${@:-"/bin/bash"}" )

echo
echo "Launching '${IMAGE}'"
echo " mounting '${REPO_DIR}' at '${MOUNT_POINT}'"
echo " running  '${COMMAND[*]}'"
echo

docker run \
  --platform linux/amd64 \
  --volume "${REPO_DIR}:${MOUNT_POINT}" \
  --workdir "${MOUNT_POINT}" \
  -it "${IMAGE}" \
  "${COMMAND[@]}"
