#!/usr/bin/env bash
set -eu -o pipefail

REPO_DIR="$( cd "$( dirname "${0}" )" && cd .. && pwd )"

(
  go install -v github.com/golangci/golangci-lint/cmd/golangci-lint@latest
)
go_bin_path="$(go env GOPATH)/bin" # TODO this should be handled in the docker container
export PATH=${go_bin_path}:${PATH}

golangci-lint version

linted_os_list=(linux windows)

go_mod_dirs="$(find "${REPO_DIR}" -type d \( -name vendor -o -name pkg \) -prune -o -name go.mod -exec dirname {} \;)"

for go_mod_dir in ${go_mod_dirs[*]}; do
  echo -e "\n lint-ing in '${go_mod_dir}' ..."
  (
    cd "${go_mod_dir}"
    for os in ${linted_os_list[*]}; do
      echo -e "          with GOOS=${os} ..."
      (
        GOOS="${os}" golangci-lint run "${1:-./...}"
      )
    done
  )
done
