#!/usr/bin/env bash
set -eu -o pipefail

REPO_DIR="$( cd "$( dirname "${0}" )" && cd .. && pwd )"

src_dirs=(src/bosh-dns src/debug src/bosh-dns/acceptance_tests/dns-acceptance-release/src/test-recursor)

for src_dir in ${src_dirs[*]}; do
  echo -e "\n lint-ing in '${src_dir}' ..."
  (
    cd "${REPO_DIR}/${src_dir}"
    "${REPO_DIR}/scripts/lint"
  )
done
