#!/bin/bash
set -e -o pipefail

REPO_DIR="$( cd "$( dirname "${0}" )" && cd .. && pwd )"

# workers exits 1 if not logged in
fly -t production workers || fly -t production login

fly -t production execute -x --privileged \
  --tag=dns-performance \
  --config=./ci/tasks/test-performance.yml \
  --inputs-from=bosh-dns-release/test-performance \
  --input=bosh-dns-release="${REPO_DIR}/../"
