#!/bin/bash

main() {
		set -eu -o pipefail -x

		DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

		export GOPATH
		GOPATH="$(cd "$DIR/.." && pwd)"
		export PATH=$GOPATH/bin:$PATH

		go install bosh-dns/vendor/github.com/onsi/ginkgo/ginkgo

		local recursive_flag='-r'
		local packages="src/bosh-dns"

		if [[ "$#" -gt 0 ]]; then
				recursive_flag=''
				packages=$*
		fi

		ginkgo -p $recursive_flag -randomizeAllSpecs -randomizeSuites -keepGoing -race -skipPackage=acceptance_tests,performance_tests,test_yml_assets,vendor $packages
}

main "$@"
