#!/bin/bash
set -eu -o pipefail

set -x

REPO_DIR="$( cd "$( dirname "${0}" )" && cd .. && pwd )"

grep -ri panic src/bosh-dns \
  --exclude-dir vendor \
  --exclude-dir test_yml_assets \
  --exclude-dir performance_tests \
  --exclude-dir acceptance_tests \
  --exclude-dir integration-tests \
  --exclude-dir gomega-dns && echo "panics detected in the code -- remove them" && exit 1

"${REPO_DIR}/scripts/lint-all"

pushd src/bosh-dns
  go run github.com/onsi/ginkgo/ginkgo -r -randomizeAllSpecs -randomizeSuites -keepGoing -race -skipPackage=acceptance_tests,integration-tests,performance_tests,test_yml_assets,vendor .
  go run github.com/onsi/ginkgo/ginkgo -r -randomizeAllSpecs -randomizeSuites -keepGoing -race integration-tests
popd

pushd src/debug
  go run github.com/onsi/ginkgo/ginkgo -p -r -randomizeAllSpecs -randomizeSuites -keepGoing -race -skipPackage=vendor .
popd
