// Code generated by counterfeiter. DO NOT EDIT.
package handlersfakes

import (
	"bosh-dns/dns/server/handlers"
	"sync"

	"github.com/miekg/dns"
)

type FakeServerMux struct {
	HandleStub        func(string, dns.Handler)
	handleMutex       sync.RWMutex
	handleArgsForCall []struct {
		arg1 string
		arg2 dns.Handler
	}
	HandleRemoveStub        func(string)
	handleRemoveMutex       sync.RWMutex
	handleRemoveArgsForCall []struct {
		arg1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeServerMux) Handle(arg1 string, arg2 dns.Handler) {
	fake.handleMutex.Lock()
	fake.handleArgsForCall = append(fake.handleArgsForCall, struct {
		arg1 string
		arg2 dns.Handler
	}{arg1, arg2})
	stub := fake.HandleStub
	fake.recordInvocation("Handle", []interface{}{arg1, arg2})
	fake.handleMutex.Unlock()
	if stub != nil {
		fake.HandleStub(arg1, arg2)
	}
}

func (fake *FakeServerMux) HandleCallCount() int {
	fake.handleMutex.RLock()
	defer fake.handleMutex.RUnlock()
	return len(fake.handleArgsForCall)
}

func (fake *FakeServerMux) HandleCalls(stub func(string, dns.Handler)) {
	fake.handleMutex.Lock()
	defer fake.handleMutex.Unlock()
	fake.HandleStub = stub
}

func (fake *FakeServerMux) HandleArgsForCall(i int) (string, dns.Handler) {
	fake.handleMutex.RLock()
	defer fake.handleMutex.RUnlock()
	argsForCall := fake.handleArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeServerMux) HandleRemove(arg1 string) {
	fake.handleRemoveMutex.Lock()
	fake.handleRemoveArgsForCall = append(fake.handleRemoveArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.HandleRemoveStub
	fake.recordInvocation("HandleRemove", []interface{}{arg1})
	fake.handleRemoveMutex.Unlock()
	if stub != nil {
		fake.HandleRemoveStub(arg1)
	}
}

func (fake *FakeServerMux) HandleRemoveCallCount() int {
	fake.handleRemoveMutex.RLock()
	defer fake.handleRemoveMutex.RUnlock()
	return len(fake.handleRemoveArgsForCall)
}

func (fake *FakeServerMux) HandleRemoveCalls(stub func(string)) {
	fake.handleRemoveMutex.Lock()
	defer fake.handleRemoveMutex.Unlock()
	fake.HandleRemoveStub = stub
}

func (fake *FakeServerMux) HandleRemoveArgsForCall(i int) string {
	fake.handleRemoveMutex.RLock()
	defer fake.handleRemoveMutex.RUnlock()
	argsForCall := fake.handleRemoveArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeServerMux) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.handleMutex.RLock()
	defer fake.handleMutex.RUnlock()
	fake.handleRemoveMutex.RLock()
	defer fake.handleRemoveMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeServerMux) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ handlers.ServerMux = new(FakeServerMux)
