// Code generated by counterfeiter. DO NOT EDIT.
package handlersfakes

import (
	"bosh-dns/dns/server/handlers"
	"sync"
)

type FakeIPProvider struct {
	GetFQDNsStub        func(string) []string
	getFQDNsMutex       sync.RWMutex
	getFQDNsArgsForCall []struct {
		arg1 string
	}
	getFQDNsReturns struct {
		result1 []string
	}
	getFQDNsReturnsOnCall map[int]struct {
		result1 []string
	}
	HasIPStub        func(string) bool
	hasIPMutex       sync.RWMutex
	hasIPArgsForCall []struct {
		arg1 string
	}
	hasIPReturns struct {
		result1 bool
	}
	hasIPReturnsOnCall map[int]struct {
		result1 bool
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeIPProvider) GetFQDNs(arg1 string) []string {
	fake.getFQDNsMutex.Lock()
	ret, specificReturn := fake.getFQDNsReturnsOnCall[len(fake.getFQDNsArgsForCall)]
	fake.getFQDNsArgsForCall = append(fake.getFQDNsArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.GetFQDNsStub
	fakeReturns := fake.getFQDNsReturns
	fake.recordInvocation("GetFQDNs", []interface{}{arg1})
	fake.getFQDNsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeIPProvider) GetFQDNsCallCount() int {
	fake.getFQDNsMutex.RLock()
	defer fake.getFQDNsMutex.RUnlock()
	return len(fake.getFQDNsArgsForCall)
}

func (fake *FakeIPProvider) GetFQDNsCalls(stub func(string) []string) {
	fake.getFQDNsMutex.Lock()
	defer fake.getFQDNsMutex.Unlock()
	fake.GetFQDNsStub = stub
}

func (fake *FakeIPProvider) GetFQDNsArgsForCall(i int) string {
	fake.getFQDNsMutex.RLock()
	defer fake.getFQDNsMutex.RUnlock()
	argsForCall := fake.getFQDNsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeIPProvider) GetFQDNsReturns(result1 []string) {
	fake.getFQDNsMutex.Lock()
	defer fake.getFQDNsMutex.Unlock()
	fake.GetFQDNsStub = nil
	fake.getFQDNsReturns = struct {
		result1 []string
	}{result1}
}

func (fake *FakeIPProvider) GetFQDNsReturnsOnCall(i int, result1 []string) {
	fake.getFQDNsMutex.Lock()
	defer fake.getFQDNsMutex.Unlock()
	fake.GetFQDNsStub = nil
	if fake.getFQDNsReturnsOnCall == nil {
		fake.getFQDNsReturnsOnCall = make(map[int]struct {
			result1 []string
		})
	}
	fake.getFQDNsReturnsOnCall[i] = struct {
		result1 []string
	}{result1}
}

func (fake *FakeIPProvider) HasIP(arg1 string) bool {
	fake.hasIPMutex.Lock()
	ret, specificReturn := fake.hasIPReturnsOnCall[len(fake.hasIPArgsForCall)]
	fake.hasIPArgsForCall = append(fake.hasIPArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.HasIPStub
	fakeReturns := fake.hasIPReturns
	fake.recordInvocation("HasIP", []interface{}{arg1})
	fake.hasIPMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeIPProvider) HasIPCallCount() int {
	fake.hasIPMutex.RLock()
	defer fake.hasIPMutex.RUnlock()
	return len(fake.hasIPArgsForCall)
}

func (fake *FakeIPProvider) HasIPCalls(stub func(string) bool) {
	fake.hasIPMutex.Lock()
	defer fake.hasIPMutex.Unlock()
	fake.HasIPStub = stub
}

func (fake *FakeIPProvider) HasIPArgsForCall(i int) string {
	fake.hasIPMutex.RLock()
	defer fake.hasIPMutex.RUnlock()
	argsForCall := fake.hasIPArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeIPProvider) HasIPReturns(result1 bool) {
	fake.hasIPMutex.Lock()
	defer fake.hasIPMutex.Unlock()
	fake.HasIPStub = nil
	fake.hasIPReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeIPProvider) HasIPReturnsOnCall(i int, result1 bool) {
	fake.hasIPMutex.Lock()
	defer fake.hasIPMutex.Unlock()
	fake.HasIPStub = nil
	if fake.hasIPReturnsOnCall == nil {
		fake.hasIPReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.hasIPReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *FakeIPProvider) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getFQDNsMutex.RLock()
	defer fake.getFQDNsMutex.RUnlock()
	fake.hasIPMutex.RLock()
	defer fake.hasIPMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeIPProvider) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ handlers.IPProvider = new(FakeIPProvider)
