// Code generated by counterfeiter. DO NOT EDIT.
package serverfakes

import (
	"bosh-dns/dns/server"
	"context"
	"sync"
)

type FakeDNSServer struct {
	ListenAndServeStub        func() error
	listenAndServeMutex       sync.RWMutex
	listenAndServeArgsForCall []struct {
	}
	listenAndServeReturns struct {
		result1 error
	}
	listenAndServeReturnsOnCall map[int]struct {
		result1 error
	}
	ShutdownContextStub        func(context.Context) error
	shutdownContextMutex       sync.RWMutex
	shutdownContextArgsForCall []struct {
		arg1 context.Context
	}
	shutdownContextReturns struct {
		result1 error
	}
	shutdownContextReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeDNSServer) ListenAndServe() error {
	fake.listenAndServeMutex.Lock()
	ret, specificReturn := fake.listenAndServeReturnsOnCall[len(fake.listenAndServeArgsForCall)]
	fake.listenAndServeArgsForCall = append(fake.listenAndServeArgsForCall, struct {
	}{})
	fake.recordInvocation("ListenAndServe", []interface{}{})
	fake.listenAndServeMutex.Unlock()
	if fake.ListenAndServeStub != nil {
		return fake.ListenAndServeStub()
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.listenAndServeReturns
	return fakeReturns.result1
}

func (fake *FakeDNSServer) ListenAndServeCallCount() int {
	fake.listenAndServeMutex.RLock()
	defer fake.listenAndServeMutex.RUnlock()
	return len(fake.listenAndServeArgsForCall)
}

func (fake *FakeDNSServer) ListenAndServeCalls(stub func() error) {
	fake.listenAndServeMutex.Lock()
	defer fake.listenAndServeMutex.Unlock()
	fake.ListenAndServeStub = stub
}

func (fake *FakeDNSServer) ListenAndServeReturns(result1 error) {
	fake.listenAndServeMutex.Lock()
	defer fake.listenAndServeMutex.Unlock()
	fake.ListenAndServeStub = nil
	fake.listenAndServeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeDNSServer) ListenAndServeReturnsOnCall(i int, result1 error) {
	fake.listenAndServeMutex.Lock()
	defer fake.listenAndServeMutex.Unlock()
	fake.ListenAndServeStub = nil
	if fake.listenAndServeReturnsOnCall == nil {
		fake.listenAndServeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.listenAndServeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeDNSServer) ShutdownContext(arg1 context.Context) error {
	fake.shutdownContextMutex.Lock()
	ret, specificReturn := fake.shutdownContextReturnsOnCall[len(fake.shutdownContextArgsForCall)]
	fake.shutdownContextArgsForCall = append(fake.shutdownContextArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	fake.recordInvocation("ShutdownContext", []interface{}{arg1})
	fake.shutdownContextMutex.Unlock()
	if fake.ShutdownContextStub != nil {
		return fake.ShutdownContextStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.shutdownContextReturns
	return fakeReturns.result1
}

func (fake *FakeDNSServer) ShutdownContextCallCount() int {
	fake.shutdownContextMutex.RLock()
	defer fake.shutdownContextMutex.RUnlock()
	return len(fake.shutdownContextArgsForCall)
}

func (fake *FakeDNSServer) ShutdownContextCalls(stub func(context.Context) error) {
	fake.shutdownContextMutex.Lock()
	defer fake.shutdownContextMutex.Unlock()
	fake.ShutdownContextStub = stub
}

func (fake *FakeDNSServer) ShutdownContextArgsForCall(i int) context.Context {
	fake.shutdownContextMutex.RLock()
	defer fake.shutdownContextMutex.RUnlock()
	argsForCall := fake.shutdownContextArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeDNSServer) ShutdownContextReturns(result1 error) {
	fake.shutdownContextMutex.Lock()
	defer fake.shutdownContextMutex.Unlock()
	fake.ShutdownContextStub = nil
	fake.shutdownContextReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeDNSServer) ShutdownContextReturnsOnCall(i int, result1 error) {
	fake.shutdownContextMutex.Lock()
	defer fake.shutdownContextMutex.Unlock()
	fake.ShutdownContextStub = nil
	if fake.shutdownContextReturnsOnCall == nil {
		fake.shutdownContextReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.shutdownContextReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeDNSServer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.listenAndServeMutex.RLock()
	defer fake.listenAndServeMutex.RUnlock()
	fake.shutdownContextMutex.RLock()
	defer fake.shutdownContextMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeDNSServer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ server.DNSServer = new(FakeDNSServer)
