// Code generated by counterfeiter. DO NOT EDIT.
package handlersfakes

import (
	"sync"

	"github.com/miekg/dns"
)

type FakeDnsHandler struct {
	ServeDNSStub        func(w dns.ResponseWriter, r *dns.Msg)
	serveDNSMutex       sync.RWMutex
	serveDNSArgsForCall []struct {
		w dns.ResponseWriter
		r *dns.Msg
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeDnsHandler) ServeDNS(w dns.ResponseWriter, r *dns.Msg) {
	fake.serveDNSMutex.Lock()
	fake.serveDNSArgsForCall = append(fake.serveDNSArgsForCall, struct {
		w dns.ResponseWriter
		r *dns.Msg
	}{w, r})
	fake.recordInvocation("ServeDNS", []interface{}{w, r})
	fake.serveDNSMutex.Unlock()
	if fake.ServeDNSStub != nil {
		fake.ServeDNSStub(w, r)
	}
}

func (fake *FakeDnsHandler) ServeDNSCallCount() int {
	fake.serveDNSMutex.RLock()
	defer fake.serveDNSMutex.RUnlock()
	return len(fake.serveDNSArgsForCall)
}

func (fake *FakeDnsHandler) ServeDNSArgsForCall(i int) (dns.ResponseWriter, *dns.Msg) {
	fake.serveDNSMutex.RLock()
	defer fake.serveDNSMutex.RUnlock()
	return fake.serveDNSArgsForCall[i].w, fake.serveDNSArgsForCall[i].r
}

func (fake *FakeDnsHandler) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.serveDNSMutex.RLock()
	defer fake.serveDNSMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeDnsHandler) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
