// Code generated by counterfeiter. DO NOT EDIT.
package managerfakes

import (
	"bosh-dns/dns/manager"
	"sync"
)

type FakeAdapterFetcher struct {
	AdaptersStub        func() ([]manager.Adapter, error)
	adaptersMutex       sync.RWMutex
	adaptersArgsForCall []struct{}
	adaptersReturns     struct {
		result1 []manager.Adapter
		result2 error
	}
	adaptersReturnsOnCall map[int]struct {
		result1 []manager.Adapter
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAdapterFetcher) Adapters() ([]manager.Adapter, error) {
	fake.adaptersMutex.Lock()
	ret, specificReturn := fake.adaptersReturnsOnCall[len(fake.adaptersArgsForCall)]
	fake.adaptersArgsForCall = append(fake.adaptersArgsForCall, struct{}{})
	fake.recordInvocation("Adapters", []interface{}{})
	fake.adaptersMutex.Unlock()
	if fake.AdaptersStub != nil {
		return fake.AdaptersStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.adaptersReturns.result1, fake.adaptersReturns.result2
}

func (fake *FakeAdapterFetcher) AdaptersCallCount() int {
	fake.adaptersMutex.RLock()
	defer fake.adaptersMutex.RUnlock()
	return len(fake.adaptersArgsForCall)
}

func (fake *FakeAdapterFetcher) AdaptersReturns(result1 []manager.Adapter, result2 error) {
	fake.AdaptersStub = nil
	fake.adaptersReturns = struct {
		result1 []manager.Adapter
		result2 error
	}{result1, result2}
}

func (fake *FakeAdapterFetcher) AdaptersReturnsOnCall(i int, result1 []manager.Adapter, result2 error) {
	fake.AdaptersStub = nil
	if fake.adaptersReturnsOnCall == nil {
		fake.adaptersReturnsOnCall = make(map[int]struct {
			result1 []manager.Adapter
			result2 error
		})
	}
	fake.adaptersReturnsOnCall[i] = struct {
		result1 []manager.Adapter
		result2 error
	}{result1, result2}
}

func (fake *FakeAdapterFetcher) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.adaptersMutex.RLock()
	defer fake.adaptersMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeAdapterFetcher) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ manager.AdapterFetcher = new(FakeAdapterFetcher)
