---
platform: linux

inputs:
  - name: bbl-state
  - name: bosh-dns-release
  - name: docker-vars
  - name: stemcell

params:
  CI_BBL_STATE: bbl-state
  DEPLOYMENTS_OF_100: 10
  PARALLEL_DEPLOYMENTS: 5

run:
  path: bosh-dns-release/ci/tasks/test-stress/deploy-n.sh
