---
platform: linux

inputs:
  - name: bbl-state
  - name: bosh-dns-release

params:
  CI_BBL_STATE: bbl-state
  BBL_AWS_ACCESS_KEY_ID: ""
  BBL_AWS_SECRET_ACCESS_KEY: ""
  BBL_AWS_ASSUME_ROLE: ""

run:
  path: bosh-dns-release/ci/tasks/test-stress/destroy-env.sh
