---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: cloudfoundry/cf-deployment-concourse-tasks

inputs:
  - name: bbl-state
  - name: bosh-dns-release

params:
  CI_BBL_STATE: bbl-state
  DEPLOYMENTS_OF_100: 10
  PARALLEL_DEPLOYMENTS: 10

run:
  path: bosh-dns-release/ci/tasks/test-stress/run-errand.sh
