name: go
on:
  push:
  pull_request:
jobs:
  lint_bosh_dns:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    name: lint_bosh_dns
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v6
        with:
          go-version-file: src/bosh-dns/go.mod
      - uses: golangci/golangci-lint-action@v7
        with:
          working-directory: src/bosh-dns/
  lint_test_recursor:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    name: lint_test_recursor
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v6
        with:
          go-version-file: src/bosh-dns/acceptance_tests/dns-acceptance-release/src/test-recursor/go.mod
      - uses: golangci/golangci-lint-action@v7
        with:
          working-directory: src/bosh-dns/acceptance_tests/dns-acceptance-release/src/test-recursor
  lint_debug:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    name: lint_debug
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v6
        with:
          go-version-file: src/debug/go.mod
      - uses: golangci/golangci-lint-action@v7
        with:
          working-directory: src/debug/
